import { type LucideProps } from 'lucide-react'
import { ReactNode } from 'react'
import {
  BookIcon,
  BriefcaseIcon,
  BrokenLinkIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClapperBoardIcon,
  CodeIcon,
  EmailIcon,
  FlagIranIcon,
  FlagSpainIcon,
  FlagUKIcon,
  ForwardIcon,
  GamepadIcon,
  GithubIcon,
  HeadphonesIcon,
  HikingIcon,
  HomeIcon,
  InstagramIcon,
  LaptopIcon,
  LinkIcon,
  LinkedInIcon,
  LocationIcon,
  NotebookIcon,
  PlayIcon,
  SuitcaseIcon,
  TelescopeIcon,
  VideoFrameCutIcon,
  YouTubeIcon,
} from './custom'
import { IconNamesType } from './types'

export const ICONS: Record<IconNamesType, (props: LucideProps) => ReactNode> = {
  'broken-link': BrokenLinkIcon,
  book: BookIcon,
  blog: NotebookIcon,
  briefcase: BriefcaseIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-up': ChevronUpIcon,
  'clapper-board': ClapperBoardIcon,
  code: CodeIcon,
  email: EmailIcon,
  'flag-iran': FlagIranIcon,
  'flag-spain': FlagSpainIcon,
  'flag-uk': FlagUKIcon,
  forward: ForwardIcon,
  gamepad: GamepadIcon,
  github: GithubIcon,
  headphones: HeadphonesIcon,
  hiking: HikingIcon,
  home: HomeIcon,
  instagram: InstagramIcon,
  laptop: LaptopIcon,
  link: LinkIcon,
  linkedin: LinkedInIcon,
  location: LocationIcon,
  play: PlayIcon,
  suitcase: SuitcaseIcon,
  telescope: TelescopeIcon,
  'video-frame-cut': VideoFrameCutIcon,
  youtube: YouTubeIcon,
}
