import { type LucideProps } from 'lucide-react'
import { ReactNode } from 'react'
import {
  BatteryCriticalIcon,
  BatteryFullIcon,
  BatteryHalfIcon,
  BatteryLowIcon,
  BlogPostIcon,
  BookIcon,
  BriefcaseIcon,
  BrokenLinkIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClapperBoardIcon,
  CodeIcon,
  CopyIcon,
  DoubleCheckIcon,
  EmailIcon,
  FlagIranIcon,
  FlagSpainIcon,
  FlagUKIcon,
  FlameIcon,
  ForwardIcon,
  GamepadIcon,
  GithubIcon,
  HammerIcon,
  HeadphonesIcon,
  HikingIcon,
  HomeIcon,
  InstagramIcon,
  LaptopIcon,
  LightBulbIcon,
  LinkIcon,
  LinkedInIcon,
  LocationIcon,
  MenuDotsIcon,
  NotebookIcon,
  PlayIcon,
  SadIcon,
  ShareIcon,
  StarShineIcon,
  SuitcaseIcon,
  TelescopeIcon,
  VideoFrameCutIcon,
  YouTubeIcon,
} from './custom'
import { IconNamesType } from './types'

export const ICONS: Record<IconNamesType, (props: LucideProps) => ReactNode> = {
  'battery-full': BatteryCriticalIcon,
  'battery-half': BatteryFullIcon,
  'battery-low': BatteryHalfIcon,
  'battery-critical': BatteryLowIcon,
  'blog-post': BlogPostIcon,
  'broken-link': BrokenLinkIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-up': ChevronUpIcon,
  'clapper-board': ClapperBoardIcon,
  'double-check': DoubleCheckIcon,
  'flag-iran': FlagIranIcon,
  'flag-spain': FlagSpainIcon,
  'flag-uk': FlagUKIcon,
  flame: FlameIcon,
  lightbulb: LightBulbIcon,
  'menu-dots': MenuDotsIcon,
  sad: SadIcon,
  'star-shine': StarShineIcon,
  'video-frame-cut': VideoFrameCutIcon,
  blog: NotebookIcon,
  book: BookIcon,
  briefcase: BriefcaseIcon,
  code: CodeIcon,
  copy: CopyIcon,
  email: EmailIcon,
  forward: ForwardIcon,
  gamepad: GamepadIcon,
  github: GithubIcon,
  hammer: HammerIcon,
  headphones: HeadphonesIcon,
  hiking: HikingIcon,
  home: HomeIcon,
  instagram: InstagramIcon,
  laptop: LaptopIcon,
  link: LinkIcon,
  linkedin: LinkedInIcon,
  location: LocationIcon,
  play: PlayIcon,
  share: ShareIcon,
  suitcase: SuitcaseIcon,
  telescope: TelescopeIcon,
  youtube: YouTubeIcon,
}
